version: "3.9"

services:
  server:
    build: ./server
    container_name: pulse-server
    restart: unless-stopped
    ports:
      - "6969:6969"
    environment:
      - PORT=6969
      - JWT_SECRET=super-secret-pulse-key-change-this-change-in-prod
      - MONGO_URI=mongodb+srv://admin:admin@students.ll5gldx.mongodb.net/PulseDb?appName=students
    volumes:
      - ./server/uploads:/app/uploads

  client:
    build: ./client
    container_name: pulse-client
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - server
